### ISSUE TITLE
sentinel configure skips client_id

### ISSUE THREAD

**Issue by tolleiv** [AOEpeople/sentinel#4]
When running `sentinel configure` the `client_id` is skipped.

**Comment by kschu91** [comment]
I already fixed that in https://github.com/AOEpeople/sentinel/commit/9694501001c8134aefd4954663ff419ff9907efa. Will provide a new release.

**Comment by kschu91** [comment]
[v0.2.0](https://github.com/AOEpeople/sentinel/releases/tag/v0.2.0)
